### ISSUE TITLE
Typo on shoutout page

### ISSUE THREAD

**Issue by tiagoafpereira** [Marantesss/vue-automated-code-transformation#1]
https://github.com/Marantesss/vue-automated-code-transformation/blob/f4196475752f373933ef552b1f3fbadd7ad7ed91/pages/6-shout-out.md?plain=1#L18

It should read `@tiagoafpereira` instead of `@tiagofpereira `(the URL is correct though!)

**Comment by Marantesss** [comment]
👿 Fixed on https://github.com/Marantesss/vue-automated-code-transformation/commit/99ba13d8befdca68207deb1ab80456f30907e228
